CREATE DATABASE CLINICA 
USE CLINICA 
CREATE TABLE PACIENTE (
NUMERO_BENIFICIARIO INT           NOT NULL,
NOME                VARCHAR (100)  NOT NULL,
LOUGRADOURO         VARCHAR (200)  NOT NULL,
NUMERO              INT            NOT NULL,
CEP                 CHAR    (08)   NOT NULL,
COMPLEMENTO         VARCHAR (255)  NOT NULL,
TELEFONE            VARCHAR (11)   NOT NULL
PRIMARY KEY (NUMERO_BENIFICIARIO)
)
GO
CREATE TABLE ESPECIALIDADE(
ID                   INT   NOT NULL,
ESPECIALIDADE        VARCHAR(100) NOT NULL
PRIMARY KEY (ID)
)

GO
CREATE TABLE MEDICO(
CODIGO       INT            NOT NULL,
NOME         VARCHAR (60)   NOT NULL,
LOUGRADOURO  VARCHAR (200)  NOT NULL,
NUMERO       INT            NOT NULL,
CEP          CHAR     (08)  NOT NULL,
COMPLEMENTO  VARCHAR  (255) NOT NULL,
CONTATO      VARCHAR  (11)  NOT NULL,
ID          INT             NOT NULL
PRIMARY KEY(CODIGO)
FOREIGN KEY (ID) REFERENCES ESPECIALIDADE (ID)
)
GO
CREATE TABLE CONSULTA (
NUMERO_BENIFICIARIO INT          NOT NULL,
CODIGO              INT          NOT NULL,
DATA_HORA           DATETIME     NOT NULL,
OBSERVACAO          VARCHAR(255) NOT NULL
PRIMARY KEY (DATA_HORA)
FOREIGN KEY(NUMERO_BENIFICIARIO) REFERENCES PACIENTE (NUMERO_BENIFICIARIO),
FOREIGN KEY (CODIGO) REFERENCES MEDICO (CODIGO)
)
INSERT INTO PACIENTE(NUMERO_BENIFICIARIO,NOME, LOUGRADOURO, NUMERO, CEP,COMPLEMENTO,TELEFONE)
              VALUES(99901,'Washington Silva','R.Anhaia',150,02345000,'casa',922229999)

INSERT INTO PACIENTE(NUMERO_BENIFICIARIO,NOME, LOUGRADOURO, NUMERO, CEP,COMPLEMENTO,TELEFONE)
              VALUES(99902,'Luis Ricardo','R.Volutários da Pátria',2251,03254010,'Bloco B. APTO 25',923450987)

 INSERT INTO PACIENTE(NUMERO_BENIFICIARIO,NOME, LOUGRADOURO, NUMERO, CEP,COMPLEMENTO,TELEFONE)
              VALUES(99904,'Maria Elisa','Av. águia de Haia',1188,06987020,'APTO 1208',912348765)

INSERT INTO PACIENTE(NUMERO_BENIFICIARIO,NOME, LOUGRADOURO, NUMERO, CEP,COMPLEMENTO,TELEFONE)
              VALUES(99905,'José Araujo','R.XV de Novembro',18,03678000,'Casa',945674312)

INSERT INTO PACIENTE(NUMERO_BENIFICIARIO,NOME, LOUGRADOURO, NUMERO, CEP,COMPLEMENTO,TELEFONE)
              VALUES(99906,'Joana Paula','R.7 de Abril',97,01214000,'Conjunto 3-apto 801',912095674)

INSERT INTO MEDICO(CODIGO,NOME,LOUGRADOURO,NUMERO,CEP,COMPLEMENTO,CONTATO,ID)
           VALUES(100001,'Ana Paula', 'R.7 DE SETEMBRO',256,0369800,'CASA',915689456,1)

INSERT INTO MEDICO(CODIGO,NOME,LOUGRADOURO,NUMERO,CEP,COMPLEMENTO,CONTATO,ID)
           VALUES(100002,'Maria Aparecida', 'AV.Brasil ',32,02145070,'CASA',923235454,1)

INSERT INTO MEDICO(CODIGO,NOME,LOUGRADOURO,NUMERO,CEP,COMPLEMENTO,CONTATO,ID)
           VALUES(100003,'Lucas Borges', 'AV.Estado ',3210,05241000,'APTO 205',936398585,2)

INSERT INTO MEDICO(CODIGO,NOME,LOUGRADOURO,NUMERO,CEP,COMPLEMENTO,CONTATO,ID)
           VALUES(100004,'Gabriel Oliverira ', 'AV.DOM Helder Camara ',350,03145000,'APTO 602',932458745,3)

INSERT INTO ESPECIALIDADE(ID,ESPECIALIDADE)
            VALUES(1,'Otorrinolaringologista')

INSERT INTO ESPECIALIDADE(ID,ESPECIALIDADE)
            VALUES(2,'Urologista')

INSERT INTO ESPECIALIDADE(ID,ESPECIALIDADE)
            VALUES(3,'Geriatria')

INSERT INTO ESPECIALIDADE(ID,ESPECIALIDADE)
            VALUES(4,'Pediatria')

INSERT INTO CONSULTA(NUMERO_BENIFICIARIO,CODIGO,DATA_HORA,OBSERVACAO)
             VALUES(99901,100002,'2021-09-04 13:20','Infecção Urinaria')

INSERT INTO CONSULTA(NUMERO_BENIFICIARIO,CODIGO,DATA_HORA,OBSERVACAO)
             VALUES(99902,100003,'2021-09-04 13:15','GRIPE')

alter table medico 
ADD dia_atendimento Varchar(200) 

update MEDICO
set dia_atendimento='Passa a atender na 2º feira'
where CODIGO=100001

update MEDICO
set dia_atendimento='Passa a atender na 4º feira'
where CODIGO=100002

update MEDICO
set dia_atendimento='Passa a atender na 2º feira'
where CODIGO=100003

update MEDICO
set dia_atendimento='Passa a atender na 5º feira'
where CODIGO= 100004

Delete ESPECIALIDADE
where ID=4

Update MEDICO
set LOUGRADOURO='AV. bras Leme',NUMERO=876,CEP=02122000,COMPLEMENTO='APTO 504'
where nome= 'Lucas Borges'

select*from MEDICO

ALTER TABLE CONSULTA
ALTER COLUMN OBSERVACAO VARCHAR(200) NOT NULL

SELECT *FROM CONSULTA

EXEC sp_help CONSULTA